[package]
name = "jvm"
version = "0.1.0"
authors = ["lnh <lnhcode@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
