name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: version
      run: rustc --version
    - name: fmt
      run: cargo fmt --all -- --check
    - name: test
      run: cargo test --verbose
