name: test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [1.37.0]

    steps:
    - uses: actions/checkout@v1
    - name: show rust version
      run: rustc --version
    - name: rust check format
      run: cargo fmt --all -- --check
    - name: rust test
      run: cargo test --verbose
