name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # https://hub.docker.com/_/rust
      image: rust:1.38-alpine 
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: format
      run: cargo fmt --all -- --check
    - name: test
      run: cargo test --verbose
