name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: fmt
      run: cargo fmt --all -- --check
    - name: test
      run: cargo test --verbose
